### ISSUE TITLE
Conduct Research for User Management

### ISSUE THREAD

**Issue by aron4** [amosproj/amos2021ws05-fin-prod-port-quick-check#11]
## User story
1. As a developer
2. I need a clear structure of user management 
3. So that I can implement roles and allocate access rights in the correct way 

## Acceptance criteria
* Create role diagram
* Define different roles 
* Describe rights of each role (admin, project manager, user) 

## Definition of done
* Approved by product owner

**Comment by aron4** [comment]
# Daten veschlüsselt gespeichert?
# stateless or stateful auth?

**Comment by ibutrons** [comment]
> * Daten veschlüsselt gespeichert?
> * stateless or stateful auth?

Authentification is not the same as User and Role Management.

**Comment by ibutrons** [comment]
> > * Daten veschlüsselt gespeichert?
> > * stateless or stateful auth?
> 
> Authentification is not the same as User and Role Management.

Indeed Athentification is followed by User and Rolles Access Management

**Comment by ibutrons** [comment]
Doc to review is ready to be reviewed, Doc is available on our shared File but also [here](https://docs.google.com/document/d/10hYqc9iyXZm-lPVatXp3FD9oQ7nBGSUivD46r0PkUQ0/edit):

**Comment by m4xrdk** [comment]
![Usermanagement](https://user-images.githubusercontent.com/73899579/143243874-50435bb4-9ff4-40ce-a5a4-58f69e540086.PNG)
