### ISSUE TITLE
Write code documentation for backend (final code)

### ISSUE THREAD

**Issue by batogami** [amosproj/amos2021ws05-fin-prod-port-quick-check#122]
## User story
1. As a developer
2. I need documented code
3. So that I easily understand what the code should do

## Acceptance criteria
- [ ] Javadoc is written for all classes and functions

## Definition of done
- [ ]     Approved by product owner
- [ ]     Code has been peer reviewed and approved
- [ ]     No syntax or runtime errors emerged
- [ ]     Code has to be included in the release candidate

**Comment by m4xrdk** [comment]
Redundant
