### ISSUE TITLE
Finish documentation and wiki

### ISSUE THREAD

**Issue by batogami** [amosproj/amos2021ws05-fin-prod-port-quick-check#128]
## User story
1. As bearing point
2. I need documentation
3. So I understand what this students did

## Acceptance criteria
- [ ] All wiki pages are understandable
- [ ] All wiki pages contain the necessary information to run an maintain this program 
- [ ] User Documentation is finalized
- [ ] (Technical) Design Documentation is finalized
- [ ] Build/Deploy Documentation is finalized
- [ ] Wiki is finalized

## Definition of done
*  Approved by product owner
* "Code" has been peer reviewed and approved

**Comment by m4xrdk** [comment]
Closed because its duplicated
