### ISSUE TITLE
Define Minimal Requirements (User Stories)

### ISSUE THREAD

**Issue by aron4** [amosproj/amos2021ws05-fin-prod-port-quick-check#17]
## User story
1. As a developer
2. I want clear definition of tasks
3. So that a first software pipeline can be established

## Acceptance criteria
* Define a clear to-do list in order to set up a first pipeline

## Definition of done
* Approved by Product Owner

**Comment by m4xrdk** [comment]
[Flowchart Bearing Point(2).pdf](https://github.com/amosproj/amos2021ws05-fin-prod-port-quick-check/files/7595781/Flowchart.Bearing.Point.2.pdf)

**Comment by m4xrdk** [comment]
![Flowchart](https://user-images.githubusercontent.com/73899579/143243357-daf09959-f9ff-48b6-885b-57160eb3094d.PNG)
