### ISSUE TITLE
Product area page - Show product variants for products 

### ISSUE THREAD

**Issue by m4xrdk** [amosproj/amos2021ws05-fin-prod-port-quick-check#193]
## User story
1. As a user 
2. I want to see the variants for products 
3. So that i can rate the different variants afterwards

## Acceptance criteria

- [x] its possible to see variants for products (maybe by clicking on them)

## Definition of done
* Approved by product owner
* Tests have been written (e.g. Unit test, integration test etc..)
* Code has been peer reviewed and approved
* No syntax or runtime errors emerged
* Code has to be included in the release candidate

**Comment by tobbber** [comment]
we currently cannot create new product variants for existing products. this issue is blocked until we can.
