### ISSUE TITLE
Select Corporate Business / Private Customer Business

### ISSUE THREAD

**Issue by aron4** [amosproj/amos2021ws05-fin-prod-port-quick-check#28]
## User story
1. As a consultant
2. I want to structure products into corporate business and private customer business areas
3. So that I can enhance the organization of products

## Acceptance criteria
* Corporate business needs to be selectable 
* Private customer Business needs to be selectable
* ...

## Definition of done
* Added only after week 5
* The same for all features

**Comment by batogami** [comment]
Issues was aborted
