### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by m4xrdk** [amosproj/amos2021ws05-fin-prod-port-quick-check#41]
## User story
1. As a developer
2. I need a use case diagram
3. So that I know the different types of users, their interactions between each other and set of actions

## Acceptance criteria
* All known users are illustrated
* All known actions are illustrated
* Their interactions are illustrated

## Definition of done
* Approved by product owner

**Comment by aron4** [comment]
- Arrow points in wrong direction
- Add consultant tasks: Create products / variants
- Add consultant tasks: Add products to projects

**Comment by m4xrdk** [comment]
![UseCase](https://user-images.githubusercontent.com/73899579/143246732-ebbb2b14-5856-485b-a12e-c57cb18c7d5e.PNG)
