### ISSUE TITLE
Create View "Manage Project"

### ISSUE THREAD

**Issue by m4xrdk** [amosproj/amos2021ws05-fin-prod-port-quick-check#45]
## User story
1. As a consultant
2. I want project page 
3. So that I can manage the project settings

## Acceptance criteria
* View must contain a field to input and edit project name
* View must contain field showing project members 
* View must contain button to add / edit members and forward to "Manage Project Members"
* View must contain caption "Bereiche" and options to select product areas
* View must contain switch to show either private business or corporate business areas
* View must contain a button to save changes
* View should be able to communicate with backend (return generic / sample values)

## Definition of done
* Approved by product owner
* Code has been peer reviewed and approved
* No syntax or runtime errors emerged
* Code has to be included in the release candidate

**Comment by batogami** [comment]
@aron4 @m4xrdk Clarification need: What is a Manage Project Members?

**Comment by InesVogel** [comment]
Note for backend: 
- ProjectEntity anpassen

**Comment by aron4** [comment]
> @aron4 @m4xrdk Clarification need: What is a Manage Project Members?

It should be "'Manage Project Member' View" such that the adding / editing happens in the next view which the button should be forwarding to. It also refers to the issue with a similar name.

**Comment by InesVogel** [comment]
@aron4 do we need a cancel/back button on this view instead of the project overview page?
