### ISSUE TITLE
Create View "Project Overview"

### ISSUE THREAD

**Issue by aron4** [amosproj/amos2021ws05-fin-prod-port-quick-check#46]
## User story
1. As a consultant
2. I want an add project view
3. So that create a project

## Acceptance criteria
* View must contain list containing all existent projects
* Each project must obtain a button to edit and forward it to "Manage Project" view
* View must contain button to add new projects and forward to "Manage Project" view
* View must contain a button to manage user (functionality not necessarily needed)
* View must contain a title
* View should be able to communicate with backend (return generic / sample values)

## Definition of done
* Added only after week 5
* The same for all features

**Comment by batogami** [comment]
Back-end: Adjust project entity class, all other functions are given

**Comment by InesVogel** [comment]
@aron4 what should the back/cancel button actually do?

**Comment by aron4** [comment]
Open: Communicate with back end
