### ISSUE TITLE
Create View "Manage Project Members"

### ISSUE THREAD

**Issue by aron4** [amosproj/amos2021ws05-fin-prod-port-quick-check#47]
## User story
1. As a consultant
2. I want to add and edit project members
3. So that I can manage project members

## Acceptance criteria
* View must contain a list including all project members
* Next to each project member there must be a editable field for e-mail 
* Next to e-mail field there must be a drop down list to choose members role (Project manager / Member)
* Next drop down list there must be a button to save / edit settings for particular member
* View must contain option to add a new member to the list
* View should be able to communicate with backend (return generic / sample values)

## Definition of done
* Approved by product owner
* Code has been peer reviewed and approved
* No syntax or runtime errors emerged
* Code has to be included in the release candidate

**Comment by InesVogel** [comment]
Note to backend 
- api definieren /users
- rest controllern implementieren 
- UserEntity überprüfen 
- UnitTest schreiben

**Comment by InesVogel** [comment]
@aron4 question with respect to the editing of email adresses: is a user allowed to have different email addresses in different projects?

**Comment by InesVogel** [comment]
@aron4 question with respect to the add button: does the user already have to be in the system to be able to add him/her to the project?
