### ISSUE TITLE
Create "Product Overview"

### ISSUE THREAD

**Issue by aron4** [amosproj/amos2021ws05-fin-prod-port-quick-check#48]
## User story
1. As a consultant
2. I want a product overview
3. So that I can manage all products in a project

## Acceptance criteria
* View must contain a tab for each product area
* View must contain a button to add products
* Products should be able to have subcategories (product variants)
* For each product / variant there should be a button to start evaluation for economical and complexity eval.
* For each product / variant the progress economical and complexity eval. should be shown
* For each product / variant there should be an option to add comments and documents
* View must contain button forwarding to result page (#66 )
* View should be able to communicate with back end (return generic / sample values)

## Definition of done
* Approved by product owner
* Code has been peer reviewed and approved
* No syntax or runtime errors emerged
* Code has to be included in the release candidate

**Comment by m4xrdk** [comment]
![Product Overview](https://user-images.githubusercontent.com/73899579/142273709-4dd893f6-63d7-4a31-a1a7-a6ff89bec635.PNG)
