### ISSUE TITLE
Create View "Economic Evaluation"

### ISSUE THREAD

**Issue by aron4** [amosproj/amos2021ws05-fin-prod-port-quick-check#62]
## User story
1. As a consultant
2. I need a economical evaluation overview of products
3. So that I can assess which products are profitable

## Acceptance criteria
* Each product should be listed
* Each product should have a rating field ("not rated", "high", "medium", "low")
* Comments and source documents from #61 should be shown / summarized
* An option to edit each products data should be available (leads to #61)
* Option to go back to product overview should be given

## Definition of done
* Added only after week 5
* The same for all features

**Comment by aron4** [comment]
![grafik](https://user-images.githubusercontent.com/92667035/142277384-ec74d464-c2ba-45d8-889b-b21125f470ec.png)

**Comment by batogami** [comment]
Issues was aborted
