### ISSUE TITLE
Create "Enter Complexity Data"

### ISSUE THREAD

**Issue by aron4** [amosproj/amos2021ws05-fin-prod-port-quick-check#64]
## User story
1. As a consultant
2. I want to enter complexity data
3. So that I can assess which products have a high complexity

## Acceptance criteria
* Contains questionnaires for different categories which are shown in tabs
* Click on tab should lead to corresponding questionnaire
* Each question is listed on a side-board and can be accessed via click-on
* Questions shown on the screen should be highlighted in the side-board
* Questions should contain 
       - a response field
       - an option to evaluate complexity
       - a comment field
       - an option to link documents
* Should contain option to save answers / forward to result page (#)

## Definition of done
* Added only after week 5
* The same for all features

**Comment by m4xrdk** [comment]
![Complexity Evaluation](https://user-images.githubusercontent.com/73899579/142280462-11b0d67a-e905-4ca8-aa62-74560481dc51.PNG)
